### PR TITLE
Complement with Phil's NF template

### PR DESCRIPTION
**Pull request by sven1103**

### CODE REVIEW

**Review by apeltzer — APPROVED** [review]
Looks all good to me

**Comment by ewels** [comment]
+1484 lines - nice! Did the template work ok? Anything that I missed / should change?

**Comment by apeltzer** [comment]
I didn't see anything missing when comparing to NGI-RNAseq. Maybe @sven1103 can say more ;-)

**Comment by sven1103** [comment]
I did not test it on a data set yet, but if it will fail at some point, I will let you know in order to update the template :)

**Pull request merged**
